a=[]
x=int(input("EnterMax Size:"))
for i in range(x):
    val=input("Enter value:")
    a.append(val)
print("orginal list is:",a)
print("Length of a list is:",len(a))
print("maximum value of the list is:",max(a))
print("Minimum value of the list is:",min(a))
b=a
print("Content of list of a is",a)
print("Content of list of b is",b)
z=input("Enter value whose index you want to get:")
index=a.index(z)
print(z,"Found at",index,"index.")
val=input("Enter value to insert:")
ind=int(input("Enter index where you want to insert:"))
a.insert(ind,val)
print(a)
val=input("Enter value to remove from the list:")
a.remove(val)
print(a)
print("Original list is:",a)
a.reverse()
print("List after reverse is:",a)
print("Last element poppped",a.pop())
