a=int(input(">>>"))
b=int(input(">>>"))
c=int(input(">>>"))
d=int(input(">>>"))
e=int(input(">>>"))
f=int(input(">>>"))
g=int(input(">>>"))
h=int(input(">>>"))
i=int(input(">>>"))
n==a==b==c==d==e==f==g==h==i
if(n+n):
    print(n+n)
if(n*n):
    print(n*n)
if(n-n):
    print(n-n)
if(n/n):
    print(n/n)